name: snake
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SAMI-AI-codes
          outputs: dist/snake.svg
      - run: |
          cp dist/snake.svg /tmp/
          git config user.name b
          git config user.email b@b.b
          git checkout -B output
          git rm -rf . || true
          cp /tmp/snake.svg snake.svg
          git add snake.svg
          git commit -m u || true
          git push -f origin output